title: Computational Neurobiology and Mathematics
description: Just somebody's notes about Computational Neurobiology and Mathematics. The project is open-source, so feel free to contribute.
baseurl: ""
url: ""
github_username:  "A-lex-Ra/alexra.github.io"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
