title: Computational Neurobiology and Mathematics
description: Fork of [vogdb's](https://github.com/vogdb) notes about Computational Neurobiology and Mathematics. The project is open-source, so feel free to contribute.
baseurl: ""
url: ""
github_username:  "A-lex-Ra"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
